name: CI
'on':
  push:
    branches:
    - main
  pull_request: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Lint
      run: pnpm lint
    - name: Test
      run: pnpm exec vitest run
    - name: Test coverage
      run: pnpm exec vitest run --coverage
    - name: Upload coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
    - name: Build
      run: pnpm build
