name: CI
'on':
  push:
    branches:
    - main
  pull_request: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Install Playwright browsers
      run: pnpm test:e2e:install
    - name: Lint
      run: pnpm lint
    - name: Test
      run: pnpm test:unit
    - name: Test coverage
      run: pnpm test:ci
    - name: Upload coverage to Codecov
      if: always()
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/coverage-final.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
    - name: Upload coverage artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage
    - name: Build
      run: pnpm build
    - name: Run E2E tests
      run: pnpm test:e2e
    - name: Upload E2E test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: test-results/
        retention-days: 30
